stages:
  - build
  - deploy

default:
  image: node:latest
  cache: &global_cache
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - node_modules/
    policy: pull
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-10 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
    - npm install --global vercel

# build 
build-package:
  stage: build
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/

# deploy
deploy-staging:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - vercel deploy --cwd dist/ --token=$VERCEL_TOKEN --yes

deploy-prod:
  stage: deploy
  rules:
      - when: manual
  script:
    - vercel deploy --cwd=dist --prod --token=$VERCEL_TOKEN --yes

